package pipeline

import (
	"encoding/json"

	agentapi "github.com/dekwanlabs/nasuta/agent"
)

// Schemas returns the strict contracts used by every pipeline handoff.
func Schemas() []agentapi.SchemaDefinition {
	return []agentapi.SchemaDefinition{
		{ID: RequestSchemaID, Version: 1, Document: json.RawMessage(`{
			"$schema":"https://json-schema.org/draft/2020-12/schema",
			"type":"object",
			"required":["feature_id","client_request_id","repository","base_ref","provider","network_enabled"],
			"properties":{
				"feature_id":{"type":"string","minLength":1,"maxLength":128},
				"client_request_id":{"type":"string","minLength":1,"maxLength":128},
				"repository":{"type":"string","minLength":1,"maxLength":512},
				"base_ref":{"type":"string","minLength":1,"maxLength":512},
				"provider":{"type":"string","minLength":1,"maxLength":64},
				"model":{"type":"string","maxLength":256},
				"network_enabled":{"type":"boolean"}
			},
			"additionalProperties":false
		}`)},
		{ID: StateSchemaID, Version: 1, Document: json.RawMessage(`{
			"$schema":"https://json-schema.org/draft/2020-12/schema",
			"type":"object",
			"required":["feature_id","options","artifacts","current_artifact"],
			"properties":{
				"feature_id":{"type":"string","minLength":1,"maxLength":128},
				"options":{"$ref":"#/$defs/options"},
				"artifacts":{"type":"array","minItems":1,"maxItems":4,"items":{"$ref":"#/$defs/artifact"}},
				"current_artifact":{"$ref":"#/$defs/artifact"},
				"implementation":{"$ref":"#/$defs/implementation"}
			},
			"additionalProperties":false,
			"$defs":{
				"options":{
					"type":"object",
					"required":["client_request_id","repository","base_ref","provider","network_enabled"],
					"properties":{
						"client_request_id":{"type":"string","minLength":1,"maxLength":128},
						"repository":{"type":"string","minLength":1,"maxLength":512},
						"base_ref":{"type":"string","minLength":1,"maxLength":512},
						"provider":{"type":"string","minLength":1,"maxLength":64},
						"model":{"type":"string","maxLength":256},
						"network_enabled":{"type":"boolean"},
						"design_artifact_id":{"type":"string","maxLength":128},
						"plan_artifact_id":{"type":"string","maxLength":128}
					},
					"additionalProperties":false
				},
				"artifact":{
					"type":"object",
					"required":["id","kind","version","content_hash"],
					"properties":{
						"id":{"type":"string","minLength":1,"maxLength":128},
						"parent_artifact_id":{"type":"string","maxLength":128},
						"kind":{"enum":["requirement_analysis","technical_proposal","system_design","implementation_plan"]},
						"version":{"type":"integer","minimum":1},
						"content_hash":{"type":"string","minLength":1,"maxLength":128}
					},
					"additionalProperties":false
				},
				"implementation":{
					"type":"object",
					"required":["id","client_request_id","status"],
					"properties":{
						"id":{"type":"string","minLength":1,"maxLength":128},
						"client_request_id":{"type":"string","minLength":1,"maxLength":128},
						"status":{"enum":["queued","preparing","running","validating","succeeded","failed","cancelled","interrupted"]}
					},
					"additionalProperties":false
				}
			}
		}`)},
		{ID: ResultSchemaID, Version: 1, Document: json.RawMessage(`{
			"$schema":"https://json-schema.org/draft/2020-12/schema",
			"type":"object",
			"required":["feature_id","artifacts","final_artifact","implementation","change_set","validation_results"],
			"properties":{
				"feature_id":{"type":"string","minLength":1,"maxLength":128},
				"artifacts":{"type":"array","minItems":4,"maxItems":4,"items":{"$ref":"#/$defs/artifact"}},
				"final_artifact":{"$ref":"#/$defs/artifact"},
				"implementation":{"$ref":"#/$defs/implementation"},
				"change_set":{"$ref":"#/$defs/change_set"},
				"validation_results":{"type":"array","items":{"$ref":"#/$defs/validation"}}
			},
			"additionalProperties":false,
			"$defs":{
				"artifact":{
					"type":"object",
					"required":["id","kind","version","content_hash"],
					"properties":{
						"id":{"type":"string","minLength":1,"maxLength":128},
						"parent_artifact_id":{"type":"string","maxLength":128},
						"kind":{"enum":["requirement_analysis","technical_proposal","system_design","implementation_plan"]},
						"version":{"type":"integer","minimum":1},
						"content_hash":{"type":"string","minLength":1,"maxLength":128}
					},
					"additionalProperties":false
				},
				"implementation":{
					"type":"object",
					"required":["id","client_request_id","status"],
					"properties":{
						"id":{"type":"string","minLength":1,"maxLength":128},
						"client_request_id":{"type":"string","minLength":1,"maxLength":128},
						"status":{"const":"succeeded"}
					},
					"additionalProperties":false
				},
				"file":{
					"type":"object",
					"required":["path","status","additions","deletions","binary"],
					"properties":{
						"path":{"type":"string"},
						"status":{"type":"string"},
						"additions":{"type":"integer","minimum":0},
						"deletions":{"type":"integer","minimum":0},
						"binary":{"type":"boolean"}
					},
					"additionalProperties":false
				},
				"deviation":{
					"type":"object",
					"required":["path","reason","explained"],
					"properties":{
						"path":{"type":"string"},
						"reason":{"type":"string"},
						"explained":{"type":"boolean"}
					},
					"additionalProperties":false
				},
				"validation":{
					"type":"object",
					"required":["sequence","status","exit_code","duration_ms","output_summary","output_bytes","timed_out"],
					"properties":{
						"sequence":{"type":"integer","minimum":1},
						"status":{"type":"string"},
						"exit_code":{"type":"integer"},
						"duration_ms":{"type":"integer","minimum":0},
						"output_summary":{"type":"string"},
						"output_rel_path":{"type":"string"},
						"output_sha256":{"type":"string"},
						"output_bytes":{"type":"integer","minimum":0},
						"timed_out":{"type":"boolean"}
					},
					"additionalProperties":false
				},
				"change_set":{
					"type":"object",
					"required":["run_id","worktree_head","patch_rel_path","patch_sha256","patch_bytes","files_changed","additions","deletions","files","plan_deviations","validation_results","provider_summary","created_at"],
					"properties":{
						"run_id":{"type":"string","minLength":1},
						"worktree_head":{"type":"string"},
						"patch_rel_path":{"type":"string"},
						"patch_sha256":{"type":"string","minLength":1},
						"patch_bytes":{"type":"integer","minimum":0},
						"files_changed":{"type":"integer","minimum":0},
						"additions":{"type":"integer","minimum":0},
						"deletions":{"type":"integer","minimum":0},
						"files":{"type":"array","items":{"$ref":"#/$defs/file"}},
						"plan_deviations":{"type":"array","items":{"$ref":"#/$defs/deviation"}},
						"validation_results":{"type":"array","items":{"$ref":"#/$defs/validation"}},
						"provider_summary":{"type":"string"},
						"created_at":{"type":"string","format":"date-time"}
					},
					"additionalProperties":false
				}
			}
		}`)},
	}
}
