package catalog

import (
	"encoding/json"

	agentapi "github.com/dekwanlabs/nasuta/agent"
)

// DefaultSchemas returns the versioned contracts shipped with the standard Agent definitions.
func DefaultSchemas() []agentapi.SchemaDefinition {
	return []agentapi.SchemaDefinition{
		{
			ID: "qa.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["question"],
				"properties":{"question":{"type":"string","minLength":1}},
				"additionalProperties":false
			}`),
		},
		{
			ID: "qa.answer", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"string",
				"minLength":1
			}`),
		},
		{
			ID: "investigation.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["question"],
				"properties":{"question":{"type":"string","minLength":1,"maxLength":8000}},
				"additionalProperties":false
			}`),
		},
		{
			ID: "task.contract", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["objective"],
				"properties":{
					"task_id":{"type":"string","minLength":1},
					"question":{"type":"string","minLength":1,"maxLength":8000},
					"objective":{"type":"string","minLength":1,"maxLength":8000},
					"capability":{"type":"string","maxLength":128,"pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"},
					"parent_question_summary":{"type":"string","minLength":1,"maxLength":8000},
					"focus_facets":{
						"type":"array",
						"maxItems":10,
						"uniqueItems":true,
						"items":{"type":"string","pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"}
					},
					"evidence_refs":{
						"type":"array",
						"maxItems":20,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1,"maxLength":256}
					},
					"delegation_id":{"type":"string","minLength":1,"maxLength":64},
					"parent_run_id":{"type":"string","minLength":1,"maxLength":64},
					"task_index":{"type":"integer","minimum":0},
					"entities":{
						"type":"array",
						"maxItems":50,
						"items":{
							"type":"object",
							"required":["id"],
							"properties":{
								"id":{"type":"string","minLength":1},
								"label":{"type":"string","minLength":1,"maxLength":256},
								"role":{"type":"string","minLength":1,"maxLength":128},
								"aliases":{
									"type":"array","maxItems":20,"uniqueItems":true,
									"items":{"type":"string","minLength":1,"maxLength":256}
								}
							},
							"additionalProperties":false
						}
					},
					"investigation_goals":{
						"type":"array",
						"maxItems":4,
						"items":{
							"type":"object",
							"required":["id","objective","independently_useful","depends_on"],
							"properties":{
								"id":{"type":"string","pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"},
								"objective":{"type":"string","minLength":1,"maxLength":500},
								"independently_useful":{"type":"boolean"},
								"depends_on":{
									"type":"array",
									"maxItems":3,
									"uniqueItems":true,
									"items":{"type":"string","pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"}
								}
							},
							"additionalProperties":false
						}
					},
					"evidence_goals":{
						"type":"array",
						"maxItems":50,
						"items":{
							"type":"object",
							"required":["id","facet","required","sources","freshness","minimum_coverage"],
							"properties":{
								"id":{"type":"string","minLength":1},
								"facet":{"type":"string","minLength":1},
								"required":{"type":"boolean"},
								"sources":{
									"type":"array",
									"maxItems":4,
									"uniqueItems":true,
									"items":{"enum":["internal","memory","web","runtime"]}
								},
								"required_sources":{
									"type":"array",
									"maxItems":4,
									"uniqueItems":true,
									"items":{"enum":["internal","memory","web","runtime"]}
								},
								"freshness":{"enum":["stable","current","bounded_live"]},
								"minimum_coverage":{"type":"integer","minimum":1,"maximum":50},
								"high_risk":{"type":"boolean"}
							},
							"additionalProperties":false
						}
					},
					"task_evidence_assignments":{
						"type":"array",
						"maxItems":5,
						"items":{"$ref":"#/$defs/task_evidence_assignment"}
					},
					"context":{"$ref":"#/$defs/context"}
				},
				"allOf":[{
					"if":{"required":["task_id"]},
					"then":{"required":["task_id","objective","entities","evidence_goals","context"]},
					"else":{"required":[
						"capability",
						"objective",
						"parent_question_summary",
						"focus_facets",
						"evidence_refs",
						"delegation_id",
						"parent_run_id",
						"task_index"
					]}
				}],
				"additionalProperties":false,
				"$defs":{
					"context":{
						"type":"object",
						"properties":{
							"conversation_refs":{
								"type":"array",
								"maxItems":100,
								"items":{"$ref":"#/$defs/conversation_ref"}
							},
							"time_range":{"$ref":"#/$defs/time_range"},
							"seed_material":{
								"type":"array",
								"maxItems":20,
								"items":{"$ref":"#/$defs/context_block"}
							}
						},
						"additionalProperties":false
					},
					"conversation_ref":{
						"type":"object",
						"properties":{
							"session_id":{"type":"string","minLength":1},
							"run_id":{"type":"string","minLength":1},
							"turn":{"type":"integer","minimum":1}
						},
						"minProperties":1,
						"additionalProperties":false
					},
					"time_range":{
						"type":"object",
						"required":["from","to","to_exclusive"],
						"properties":{
							"from":{"type":"string","format":"date-time"},
							"to":{"type":"string","format":"date-time"},
							"to_exclusive":{"type":"boolean"},
							"raw":{"type":"string"}
						},
						"additionalProperties":false
					},
					"coverage":{
						"type":"object",
						"properties":{
							"complete":{"type":"boolean"},
							"partial":{"type":"boolean"},
							"included":{"type":"integer","minimum":0},
							"omitted_items":{"type":"integer","minimum":0},
							"next_cursor":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence":{
						"type":"object",
						"required":["source_kind","target","coverage"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"sections":{"type":"array","items":{"type":"string","minLength":1}},
							"content_hash":{"type":"string"},
							"coverage":{"$ref":"#/$defs/coverage"},
							"facets":{"type":"array","items":{"type":"string","minLength":1}},
							"trust_tier":{"type":"integer","minimum":0},
							"evidence_class":{"type":"string"},
							"token_cost":{"type":"integer","minimum":0},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"reference":{
						"type":"object",
						"required":["type","target"],
						"properties":{
							"type":{"type":"string","minLength":1},
							"label":{"type":"string"},
							"target":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					},
					"evidence_identity":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_ref":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"},
							"content_hash":{"type":"string"}
						},
						"additionalProperties":false
					},
					"task_context_ref":{
						"type":"object",
						"required":["source","content_hash"],
						"properties":{
							"source":{"type":"string","minLength":1},
							"content_hash":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					},
					"task_evidence_assignment":{
						"type":"object",
						"required":["task_id","input_refs","context_refs"],
						"properties":{
							"task_id":{"type":"string","pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"},
							"required_facets":{
								"type":"array",
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"input_refs":{
								"type":"array",
								"maxItems":200,
								"items":{"$ref":"#/$defs/evidence_ref"}
							},
							"context_refs":{
								"type":"array",
								"maxItems":20,
								"items":{"$ref":"#/$defs/task_context_ref"}
							}
						},
						"additionalProperties":false
					},
					"evidence_conflict":{
						"type":"object",
						"required":["identity","current","incoming"],
						"properties":{
							"identity":{"$ref":"#/$defs/evidence_identity"},
							"current":{"$ref":"#/$defs/evidence"},
							"incoming":{"$ref":"#/$defs/evidence"},
							"current_origin":{"type":"string"},
							"incoming_origin":{"type":"string"}
						},
						"additionalProperties":false
					},
					"context_block":{
						"type":"object",
						"required":["source","title","content","complete","content_hash"],
						"properties":{
							"source":{"type":"string","minLength":1},
							"title":{"type":"string","minLength":1},
							"content":{"type":"string","maxLength":200000},
							"references":{
								"type":"array",
								"maxItems":200,
								"items":{"$ref":"#/$defs/reference"}
							},
							"evidence":{
								"type":"array",
								"maxItems":200,
								"items":{"$ref":"#/$defs/evidence"}
							},
							"evidence_conflicts":{
								"type":"array",
								"maxItems":100,
								"items":{"$ref":"#/$defs/evidence_conflict"}
							},
							"complete":{"type":"boolean"},
							"content_hash":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "investigation.report", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["focus","summary","findings","gaps","covered_goals","unresolved_goals"],
				"properties":{
					"focus":{"enum":["code","runtime","docs","web","memory"]},
					"summary":{"type":"string","minLength":1},
					"findings":{"type":"array","maxItems":50,"items":{"$ref":"#/$defs/finding"}},
					"gaps":{"type":"array","maxItems":20,"items":{"type":"string","minLength":1}},
					"covered_goals":{
						"type":"array",
						"maxItems":50,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					},
					"unresolved_goals":{
						"type":"array",
						"maxItems":50,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					}
				},
				"additionalProperties":false,
				"$defs":{
					"evidence_identity":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence":{
						"type":"object",
						"required":["kind","reference","summary"],
						"properties":{
							"kind":{"type":"string","minLength":1},
							"reference":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1},
							"evidence_id":{"type":"string","pattern":"^ev_[a-f0-9]{64}$"},
							"identity":{"$ref":"#/$defs/evidence_identity"}
						},
						"additionalProperties":false
					},
					"finding":{
						"type":"object",
						"required":["claim","goal_ids","evidence","confidence"],
						"properties":{
							"claim":{"type":"string","minLength":1},
							"entity_ids":{
								"type":"array",
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"goal_ids":{
								"type":"array",
								"minItems":1,
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{"$ref":"#/$defs/evidence"}},
							"confidence":{"type":"number","minimum":0,"maximum":1}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "delegation.report", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["capability","status","completeness","usage"],
				"properties":{
					"run_id":{"type":"string","minLength":1,"maxLength":128},
					"report_id":{"type":"string","minLength":1,"maxLength":128},
					"capability":{
						"type":"string",
						"maxLength":128,
						"pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"
					},
					"status":{"enum":["completed","partial","failed","timeout","cancelled","rejected","interrupted"]},
					"completeness":{"enum":["complete","partial"]},
					"summary":{"type":"string","maxLength":16000},
					"findings":{
						"type":"array",
						"maxItems":20,
						"items":{"$ref":"#/$defs/finding"}
					},
					"conflicts":{
						"type":"array",
						"maxItems":10,
						"items":{"$ref":"#/$defs/conflict"}
					},
					"uncertainties":{
						"type":"array",
						"maxItems":10,
						"items":{"type":"string","minLength":1,"maxLength":2000}
					},
					"usage":{"$ref":"#/$defs/usage"},
					"error":{"$ref":"#/$defs/error"}
				},
				"allOf":[{
					"if":{"properties":{"status":{"const":"completed"}},"required":["status"]},
					"then":{"properties":{"completeness":{"const":"complete"}}}
				}],
				"additionalProperties":false,
				"$defs":{
					"structured_claim":{
						"type":"object",
						"required":["schema","subject","predicate","value"],
						"properties":{
							"schema":{"type":"string","minLength":1,"maxLength":128},
							"subject":{"type":"string","minLength":1,"maxLength":1000},
							"predicate":{"type":"string","minLength":1,"maxLength":256},
							"value":{},
							"scope":{"type":"object","maxProperties":20}
						},
						"additionalProperties":false
					},
					"finding":{
						"type":"object",
						"required":["id","statement","confidence","citations"],
						"properties":{
							"id":{"type":"string","minLength":1,"maxLength":128},
							"statement":{"type":"string","minLength":1,"maxLength":8000},
							"structured_claim":{"$ref":"#/$defs/structured_claim"},
							"confidence":{"enum":["low","medium","high"]},
							"citations":{
								"type":"array",
								"minItems":1,
								"maxItems":20,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1,"maxLength":256}
							},
							"facets":{
								"type":"array",
								"maxItems":10,
								"uniqueItems":true,
								"items":{
									"type":"string",
									"pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"
								}
							},
							"critical":{"type":"boolean"}
						},
						"additionalProperties":false
					},
					"conflict":{
						"type":"object",
						"required":["kind","claim_ids"],
						"properties":{
							"id":{"type":"string","minLength":1,"maxLength":128},
							"kind":{"type":"string","minLength":1,"maxLength":128},
							"claim_ids":{
								"type":"array",
								"minItems":2,
								"maxItems":20,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1,"maxLength":256}
							},
							"critical":{"type":"boolean"}
						},
						"additionalProperties":false
					},
					"usage":{
						"type":"object",
						"required":["tool_calls","input_tokens","output_tokens","total_tokens"],
						"properties":{
							"tool_calls":{"type":"integer","minimum":0},
							"input_tokens":{"type":"integer","minimum":0},
							"output_tokens":{"type":"integer","minimum":0},
							"reasoning_tokens":{"type":"integer","minimum":0},
							"total_tokens":{"type":"integer","minimum":0},
							"cost_micros":{"type":"integer","minimum":0}
						},
						"additionalProperties":false
					},
					"error":{
						"type":"object",
						"required":["code","message","retryable"],
						"properties":{
							"code":{"type":"string","minLength":1,"maxLength":128},
							"message":{"type":"string","minLength":1,"maxLength":4000},
							"retryable":{"type":"boolean"}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "delegation.verification.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["question","decision_question","claims","conflicts","evidence_refs","reasons"],
				"properties":{
					"question":{"type":"string","minLength":1,"maxLength":4000},
					"decision_question":{"type":"string","minLength":1,"maxLength":2000},
					"claims":{
						"type":"array",
						"maxItems":40,
						"items":{
							"type":"object",
							"required":["id","statement","citations"],
							"properties":{
								"id":{"type":"string","minLength":1,"maxLength":256},
								"statement":{"type":"string","minLength":1,"maxLength":8000},
								"critical":{"type":"boolean"},
								"citations":{
									"type":"array",
									"maxItems":20,
									"uniqueItems":true,
									"items":{"type":"string","minLength":1,"maxLength":256}
								}
							},
							"additionalProperties":false
						}
					},
					"conflicts":{
						"type":"array",
						"maxItems":20,
						"items":{
							"type":"object",
							"required":["kind","claim_ids"],
							"properties":{
								"kind":{"type":"string","minLength":1,"maxLength":128},
								"claim_key":{"type":"string","maxLength":2000},
								"claim_ids":{
									"type":"array",
									"minItems":2,
									"maxItems":20,
									"uniqueItems":true,
									"items":{"type":"string","minLength":1,"maxLength":256}
								},
								"critical":{"type":"boolean"}
							},
							"additionalProperties":false
						}
					},
					"evidence_refs":{
						"type":"array",
						"maxItems":100,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1,"maxLength":256}
					},
					"reasons":{
						"type":"array",
						"minItems":1,
						"maxItems":20,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1,"maxLength":128}
					}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "delegation.verification.result", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["summary","verdicts","uncertainties"],
				"properties":{
					"summary":{"type":"string","minLength":1,"maxLength":8000},
					"verdicts":{
						"type":"array",
						"maxItems":40,
						"items":{
							"type":"object",
							"required":["claim_ids","decision","rationale","evidence_refs"],
							"properties":{
								"claim_ids":{
									"type":"array",
									"minItems":1,
									"maxItems":20,
									"uniqueItems":true,
									"items":{"type":"string","minLength":1,"maxLength":256}
								},
								"decision":{"enum":["supported","contradicted","distinct","unresolved"]},
								"rationale":{"type":"string","minLength":1,"maxLength":4000},
								"evidence_refs":{
									"type":"array",
									"maxItems":20,
									"uniqueItems":true,
									"items":{"type":"string","minLength":1,"maxLength":256}
								}
							},
							"additionalProperties":false
						}
					},
					"uncertainties":{
						"type":"array",
						"maxItems":20,
						"items":{"type":"string","minLength":1,"maxLength":2000}
					}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "delegation.verification.artifact", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["status","usage"],
				"properties":{
					"run_id":{"type":"string","minLength":1,"maxLength":128},
					"verification_id":{"type":"string","minLength":1,"maxLength":128},
					"status":{"enum":["completed","partial","failed","timeout","cancelled","rejected","interrupted"]},
					"summary":{"type":"string","maxLength":8000},
					"verdicts":{
						"type":"array",
						"maxItems":40,
						"items":{
							"type":"object",
							"required":["claim_ids","decision","rationale"],
							"properties":{
								"claim_ids":{
									"type":"array",
									"minItems":1,
									"maxItems":20,
									"uniqueItems":true,
									"items":{"type":"string","minLength":1,"maxLength":256}
								},
								"decision":{"enum":["supported","contradicted","distinct","unresolved"]},
								"rationale":{"type":"string","minLength":1,"maxLength":4000},
								"evidence_refs":{
									"type":"array",
									"maxItems":20,
									"uniqueItems":true,
									"items":{"type":"string","minLength":1,"maxLength":256}
								}
							},
							"additionalProperties":false
						}
					},
					"uncertainties":{
						"type":"array",
						"maxItems":20,
						"items":{"type":"string","minLength":1,"maxLength":2000}
					},
					"usage":{
						"type":"object",
						"required":["tool_calls","input_tokens","output_tokens","total_tokens"],
						"properties":{
							"tool_calls":{"type":"integer","minimum":0},
							"input_tokens":{"type":"integer","minimum":0},
							"output_tokens":{"type":"integer","minimum":0},
							"reasoning_tokens":{"type":"integer","minimum":0},
							"total_tokens":{"type":"integer","minimum":0},
							"cost_micros":{"type":"integer","minimum":0}
						},
						"additionalProperties":false
					},
					"error":{
						"type":"object",
						"required":["code","message","retryable"],
						"properties":{
							"code":{"type":"string","minLength":1,"maxLength":128},
							"message":{"type":"string","minLength":1,"maxLength":4000},
							"retryable":{"type":"boolean"}
						},
						"additionalProperties":false
					}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "investigation.bundle", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["handoffs","evidence_units","evidence_conflicts","completeness"],
				"properties":{
					"handoffs":{
						"type":"array",
						"maxItems":50,
						"items":{"$ref":"#/$defs/handoff"}
					},
					"unavailable_tasks":{
						"type":"array",
						"maxItems":50,
						"items":{"$ref":"#/$defs/unavailable_task"}
					},
					"evidence_units":{
						"type":"array",
						"items":{"$ref":"#/$defs/evidence_unit"}
					},
					"baseline_evidence_identities":{
						"type":"array",
						"uniqueItems":true,
						"items":{"$ref":"#/$defs/evidence_identity"}
					},
					"evidence_units_total":{"type":"integer","minimum":1},
					"evidence_units_omitted":{"type":"integer","minimum":1},
					"evidence_conflicts":{
						"type":"array",
						"maxItems":100,
						"items":{"$ref":"#/$defs/evidence_conflict"}
					},
					"convergence":{"$ref":"#/$defs/convergence"},
					"completeness":{"enum":["complete","partial","unavailable"]}
				},
				"additionalProperties":false,
				"$defs":{
					"schema_ref":{
						"type":"object",
						"required":["id","version"],
						"properties":{
							"id":{"type":"string","minLength":1},
							"version":{"type":"integer","minimum":1}
						},
						"additionalProperties":false
					},
					"handoff":{
						"type":"object",
						"required":["producer_node_id","schema","payload","completeness"],
						"properties":{
							"producer_node_id":{"type":"string","minLength":1},
							"schema":{"$ref":"#/$defs/schema_ref"},
							"payload":{"$ref":"#/$defs/report"},
							"completeness":{"enum":["complete","partial","unavailable"]}
						},
						"additionalProperties":false
					},
					"unavailable_task":{
						"type":"object",
						"required":["producer_node_id"],
						"properties":{
							"producer_node_id":{"type":"string","minLength":1},
							"stop_reason":{"enum":[
								"no_new_evidence",
								"no_affordable_task",
								"duplicate_evidence_limit",
								"budget_exhausted",
								"capability_unavailable",
								"needs_clarification",
								"evidence_insufficient"
							]}
						},
						"additionalProperties":false
					},
					"convergence":{
						"type":"object",
						"required":[
							"candidate_count",
							"new_identity_count",
							"duplicate_count",
							"duplicate_ratio"
						],
						"properties":{
							"candidate_count":{"type":"integer","minimum":0},
							"new_identity_count":{"type":"integer","minimum":0},
							"duplicate_count":{"type":"integer","minimum":0},
							"duplicate_ratio":{"type":"number","minimum":0,"maximum":1},
							"max_duplicate_ratio":{"type":"number","exclusiveMinimum":0,"maximum":1}
						},
						"additionalProperties":false
					},
					"report":{
						"type":"object",
						"required":["focus","summary","findings","gaps","covered_goals","unresolved_goals"],
						"properties":{
							"focus":{"enum":["code","runtime","docs","web","memory"]},
							"summary":{"type":"string","minLength":1},
							"findings":{"type":"array","maxItems":50,"items":{"$ref":"#/$defs/finding"}},
							"gaps":{"type":"array","maxItems":20,"items":{"type":"string","minLength":1}},
							"covered_goals":{
								"type":"array",
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"unresolved_goals":{
								"type":"array",
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							}
						},
						"additionalProperties":false
					},
					"evidence":{
						"type":"object",
						"required":["kind","reference","summary"],
						"properties":{
							"kind":{"type":"string","minLength":1},
							"reference":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1},
							"evidence_id":{"type":"string","pattern":"^ev_[a-f0-9]{64}$"},
							"identity":{"$ref":"#/$defs/evidence_identity"}
						},
						"additionalProperties":false
					},
					"coverage":{
						"type":"object",
						"properties":{
							"complete":{"type":"boolean"},
							"partial":{"type":"boolean"},
							"included":{"type":"integer","minimum":0},
							"omitted_items":{"type":"integer","minimum":0},
							"next_cursor":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_unit":{
						"type":"object",
						"required":["source_kind","target","coverage"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"sections":{"type":"array","items":{"type":"string","minLength":1}},
							"content_hash":{"type":"string"},
							"coverage":{"$ref":"#/$defs/coverage"},
							"facets":{"type":"array","items":{"type":"string","minLength":1}},
							"trust_tier":{"type":"integer","minimum":0},
							"evidence_class":{"type":"string"},
							"token_cost":{"type":"integer","minimum":0},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_identity":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_conflict":{
						"type":"object",
						"required":["identity","current","incoming"],
						"properties":{
							"identity":{"$ref":"#/$defs/evidence_identity"},
							"current":{"$ref":"#/$defs/evidence_unit"},
							"incoming":{"$ref":"#/$defs/evidence_unit"},
							"current_origin":{"type":"string"},
							"incoming_origin":{"type":"string"}
						},
						"additionalProperties":false
					},
					"finding":{
						"type":"object",
						"required":["claim","goal_ids","evidence","confidence"],
						"properties":{
							"claim":{"type":"string","minLength":1},
							"entity_ids":{
								"type":"array",
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"goal_ids":{
								"type":"array",
								"minItems":1,
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{"$ref":"#/$defs/evidence"}},
							"confidence":{"type":"number","minimum":0,"maximum":1}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "investigation.verified_bundle", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":[
					"supported_claims",
					"partial_claims",
					"unsupported_claims",
					"partial_goals",
					"unresolved_goals",
					"limitations",
					"evidence_units",
					"evidence_conflicts",
					"omissions",
					"verification",
					"completeness"
				],
				"properties":{
					"supported_claims":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/supported_claim"}
					},
					"partial_claims":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/supported_claim"}
					},
					"unsupported_claims":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/unsupported_claim"}
					},
					"partial_goals":{
						"type":"array",
						"maxItems":50,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					},
					"unresolved_goals":{
						"type":"array",
						"maxItems":50,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					},
					"limitations":{
						"type":"array",
						"maxItems":100,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					},
					"evidence_units":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/evidence_unit"}
					},
					"evidence_conflicts":{
						"type":"array",
						"maxItems":100,
						"items":{"$ref":"#/$defs/evidence_conflict"}
					},
					"omissions":{
						"type":"object",
						"required":[
							"claims",
							"goals",
							"limitations",
							"evidence_units",
							"evidence_conflicts"
						],
						"properties":{
							"claims":{"type":"integer","minimum":0},
							"goals":{"type":"integer","minimum":0},
							"limitations":{"type":"integer","minimum":0},
							"evidence_units":{"type":"integer","minimum":0},
							"evidence_conflicts":{"type":"integer","minimum":0}
						},
						"additionalProperties":false
					},
					"verification":{
						"type":"object",
						"required":["decision","stop_reason"],
						"properties":{
							"decision":{"enum":["complete","partial","unavailable"]},
							"stop_reason":{"enum":[
								"required_goals_covered",
								"no_new_evidence",
								"no_affordable_task",
								"duplicate_evidence_limit",
								"verification_failed",
								"deadline_exceeded",
								"budget_exhausted",
								"capability_unavailable",
								"needs_clarification"
							]}
						},
						"additionalProperties":false
					},
					"completeness":{"enum":["complete","partial","unavailable"]}
				},
				"additionalProperties":false,
				"$defs":{
					"evidence":{
						"type":"object",
						"required":["kind","reference","summary"],
						"properties":{
							"kind":{"type":"string","minLength":1},
							"reference":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1},
							"identity":{"$ref":"#/$defs/evidence_identity"}
						},
						"additionalProperties":false
					},
					"supported_claim":{
						"type":"object",
						"required":[
							"producer_node_id",
							"finding_index",
							"claim",
							"goal_ids",
							"evidence",
							"evidence_identities",
							"confidence",
							"support",
							"high_risk"
						],
						"properties":{
							"producer_node_id":{"type":"string","minLength":1},
							"finding_index":{"type":"integer","minimum":0},
							"claim":{"type":"string","minLength":1},
							"goal_ids":{
								"type":"array",
								"minItems":1,
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"evidence":{
								"type":"array",
								"minItems":1,
								"maxItems":20,
								"items":{"$ref":"#/$defs/evidence"}
							},
							"evidence_identities":{
								"type":"array",
								"minItems":1,
								"maxItems":200,
								"uniqueItems":true,
								"items":{"$ref":"#/$defs/evidence_identity"}
							},
							"confidence":{"type":"number","minimum":0,"maximum":1},
							"support":{"enum":["supported","partial"]},
							"high_risk":{"type":"boolean"}
						},
						"additionalProperties":false
					},
					"unsupported_claim":{
						"type":"object",
						"required":[
							"producer_node_id",
							"finding_index",
							"goal_ids",
							"support",
							"high_risk",
							"reason_code"
						],
						"properties":{
							"producer_node_id":{"type":"string","minLength":1},
							"finding_index":{"type":"integer","minimum":0},
							"goal_ids":{
								"type":"array",
								"minItems":1,
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"support":{"const":"unsupported"},
							"high_risk":{"type":"boolean"},
							"reason_code":{"const":"canonical_evidence_unbound"}
						},
						"additionalProperties":false
					},
					"coverage":{
						"type":"object",
						"properties":{
							"complete":{"type":"boolean"},
							"partial":{"type":"boolean"},
							"included":{"type":"integer","minimum":0},
							"omitted_items":{"type":"integer","minimum":0},
							"next_cursor":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_unit":{
						"type":"object",
						"required":["source_kind","target","coverage"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"sections":{"type":"array","items":{"type":"string","minLength":1}},
							"content_hash":{"type":"string"},
							"coverage":{"$ref":"#/$defs/coverage"},
							"facets":{"type":"array","items":{"type":"string","minLength":1}},
							"trust_tier":{"type":"integer","minimum":0},
							"evidence_class":{"type":"string"},
							"token_cost":{"type":"integer","minimum":0},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_identity":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_conflict":{
						"type":"object",
						"required":["identity","current","incoming"],
						"properties":{
							"identity":{"$ref":"#/$defs/evidence_identity"},
							"current":{"$ref":"#/$defs/evidence_unit"},
							"incoming":{"$ref":"#/$defs/evidence_unit"},
							"current_origin":{"type":"string"},
							"incoming_origin":{"type":"string"}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "investigation.verified_bundle", Version: 2,
			Document: json.RawMessage(`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["supported_claims","partial_claims","unsupported_claims","partial_goals","unresolved_goals","limitations","evidence_units","evidence_conflicts","omissions","verification","completeness","limitations_detail"],"properties":{"supported_claims":{"type":"array","maxItems":200,"items":{"$ref":"#/$defs/supported_claim"}},"partial_claims":{"type":"array","maxItems":200,"items":{"$ref":"#/$defs/supported_claim"}},"unsupported_claims":{"type":"array","maxItems":200,"items":{"$ref":"#/$defs/unsupported_claim"}},"partial_goals":{"type":"array","maxItems":50,"uniqueItems":true,"items":{"type":"string","minLength":1}},"unresolved_goals":{"type":"array","maxItems":50,"uniqueItems":true,"items":{"type":"string","minLength":1}},"limitations":{"type":"array","maxItems":10,"uniqueItems":true,"items":{"type":"string","minLength":1}},"evidence_units":{"type":"array","maxItems":200,"items":{"$ref":"#/$defs/evidence_unit"}},"evidence_conflicts":{"type":"array","maxItems":100,"items":{"$ref":"#/$defs/evidence_conflict"}},"subject_coverage":{"type":"array","maxItems":50,"items":{"type":"object","required":["entity_id","covered_facets","missing_facets","sources","complete"],"properties":{"entity_id":{"type":"string","minLength":1},"covered_facets":{"type":"array","uniqueItems":true,"items":{"type":"string","minLength":1}},"missing_facets":{"type":"array","uniqueItems":true,"items":{"type":"string","minLength":1}},"sources":{"type":"array","uniqueItems":true,"items":{"type":"string","minLength":1}},"complete":{"type":"boolean"}},"additionalProperties":false}},"omissions":{"type":"object","required":["claims","goals","limitations","evidence_units","evidence_conflicts"],"properties":{"claims":{"type":"integer","minimum":0},"goals":{"type":"integer","minimum":0},"limitations":{"type":"integer","minimum":0},"evidence_units":{"type":"integer","minimum":0},"evidence_conflicts":{"type":"integer","minimum":0}},"additionalProperties":false},"verification":{"type":"object","required":["decision","stop_reason"],"properties":{"decision":{"enum":["complete","partial","unavailable"]},"stop_reason":{"enum":["required_goals_covered","no_new_evidence","no_affordable_task","duplicate_evidence_limit","verification_failed","deadline_exceeded","budget_exhausted","capability_unavailable","evidence_insufficient","needs_clarification"]}},"additionalProperties":false},"completeness":{"enum":["complete","partial","unavailable"]},"limitations_detail":{"type":"object","required":["artifact_id","total_count","displayed_count","omitted_count","normalization_version"],"properties":{"artifact_id":{"type":"string","pattern":"^art_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"total_count":{"type":"integer","minimum":0},"displayed_count":{"type":"integer","minimum":0},"omitted_count":{"type":"integer","minimum":0},"normalization_version":{"type":"string","minLength":1}},"additionalProperties":false}},"additionalProperties":false,"$defs":{"evidence":{"type":"object","required":["kind","reference","summary"],"properties":{"kind":{"type":"string","minLength":1},"reference":{"type":"string","minLength":1},"summary":{"type":"string","minLength":1},"identity":{"$ref":"#/$defs/evidence_identity"}},"additionalProperties":false},"supported_claim":{"type":"object","required":["producer_node_id","finding_index","claim","goal_ids","evidence","evidence_identities","confidence","support","high_risk"],"properties":{"producer_node_id":{"type":"string","minLength":1},"finding_index":{"type":"integer","minimum":0},"claim":{"type":"string","minLength":1},"goal_ids":{"type":"array","minItems":1,"maxItems":50,"uniqueItems":true,"items":{"type":"string","minLength":1}},"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{"$ref":"#/$defs/evidence"}},"evidence_identities":{"type":"array","minItems":1,"maxItems":200,"uniqueItems":true,"items":{"$ref":"#/$defs/evidence_identity"}},"confidence":{"type":"number","minimum":0,"maximum":1},"support":{"enum":["supported","partial"]},"high_risk":{"type":"boolean"}},"additionalProperties":false},"unsupported_claim":{"type":"object","required":["producer_node_id","finding_index","goal_ids","support","high_risk","reason_code"],"properties":{"producer_node_id":{"type":"string","minLength":1},"finding_index":{"type":"integer","minimum":0},"goal_ids":{"type":"array","minItems":1,"maxItems":50,"uniqueItems":true,"items":{"type":"string","minLength":1}},"support":{"const":"unsupported"},"high_risk":{"type":"boolean"},"reason_code":{"const":"canonical_evidence_unbound"}},"additionalProperties":false},"coverage":{"type":"object","properties":{"complete":{"type":"boolean"},"partial":{"type":"boolean"},"included":{"type":"integer","minimum":0},"omitted_items":{"type":"integer","minimum":0},"next_cursor":{"type":"string"}},"additionalProperties":false},"evidence_unit":{"type":"object","required":["source_kind","target","coverage"],"properties":{"source_kind":{"type":"string","minLength":1},"target":{"type":"string","minLength":1},"sections":{"type":"array","items":{"type":"string","minLength":1}},"content_hash":{"type":"string"},"coverage":{"$ref":"#/$defs/coverage"},"facets":{"type":"array","items":{"type":"string","minLength":1}},"trust_tier":{"type":"integer","minimum":0},"evidence_class":{"type":"string"},"token_cost":{"type":"integer","minimum":0},"version":{"type":"string"},"time_range":{"type":"string"}},"additionalProperties":false},"evidence_identity":{"type":"object","required":["source_kind","target"],"properties":{"source_kind":{"type":"string","minLength":1},"target":{"type":"string","minLength":1},"section":{"type":"string"},"version":{"type":"string"},"time_range":{"type":"string"}},"additionalProperties":false},"evidence_conflict":{"type":"object","required":["identity","current","incoming"],"properties":{"identity":{"$ref":"#/$defs/evidence_identity"},"current":{"$ref":"#/$defs/evidence_unit"},"incoming":{"$ref":"#/$defs/evidence_unit"},"current_origin":{"type":"string"},"incoming_origin":{"type":"string"}},"additionalProperties":false}}}`),
		},
		{
			ID: "investigation.limitations.detail", Version: 1,
			Document: json.RawMessage(`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["schema_id","schema_version","workflow_run_id","normalization_version","raw_count","deduplicated_count","merged_count","displayed_count","omitted_count","limitations"],"properties":{"schema_id":{"const":"investigation.limitations.detail"},"schema_version":{"const":1},"workflow_run_id":{"type":"string","minLength":1},"normalization_version":{"type":"string","minLength":1},"raw_count":{"type":"integer","minimum":0},"deduplicated_count":{"type":"integer","minimum":0},"merged_count":{"type":"integer","minimum":0},"displayed_count":{"type":"integer","minimum":0},"omitted_count":{"type":"integer","minimum":0},"limitations":{"type":"array","maxItems":100,"items":{"$ref":"#/$defs/limitation_record"}}},"additionalProperties":false,"$defs":{"limitation_record":{"type":"object","required":["id","text","severity","category","confidence","merge_key","displayed","rank"],"properties":{"id":{"type":"string","minLength":1},"text":{"type":"string","minLength":1},"severity":{"enum":["critical","high","medium","low"]},"category":{"type":"string","minLength":1},"confidence":{"type":"number","minimum":0,"maximum":1},"evidence_refs":{"type":"array","uniqueItems":true,"items":{"type":"string","minLength":1}},"producer_node_ids":{"type":"array","uniqueItems":true,"items":{"type":"string","minLength":1}},"merge_key":{"type":"string","minLength":1},"merged_from_ids":{"type":"array","uniqueItems":true,"items":{"type":"string","minLength":1}},"merge_reason":{"type":"string"},"merge_method":{"type":"string","minLength":1},"displayed":{"type":"boolean"},"rank":{"type":"integer","minimum":1}},"additionalProperties":false}}}`),
		},
		{
			ID: "investigation.answer", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["answer","citations","limitations"],
				"properties":{
					"answer":{"type":"string","minLength":1},
					"citations":{"type":"array","maxItems":50,"items":{
						"type":"object",
						"required":["claim","evidence"],
						"properties":{
							"claim":{"type":"string","minLength":1},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{
								"type":"object",
								"required":["kind","reference","summary"],
								"properties":{
									"kind":{"type":"string","minLength":1},
									"reference":{"type":"string","minLength":1},
									"summary":{"type":"string","minLength":1}
								},
								"additionalProperties":false
							}}
						},
						"additionalProperties":false
					}},
					"limitations":{"type":"array","maxItems":20,"items":{"type":"string","minLength":1}}
				},
				"additionalProperties":false
			}`),
		},
		{
			// Version 1 capped limitations at 20 while the verified-bundle input
			// correctly permits up to 100. Keep v1 immutable for pinned runs and
			// widen the successor so synthesis can faithfully carry all verified
			// material limitations.
			ID: "investigation.answer", Version: 2,
			CompatibleFrom: []agentapi.SchemaRef{{
				ID: "investigation.answer", Version: 1,
			}},
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["answer","citations","limitations"],
				"properties":{
					"answer":{"type":"string","minLength":1},
					"citations":{"type":"array","maxItems":50,"items":{
						"type":"object",
						"required":["claim","evidence"],
						"properties":{
							"claim":{"type":"string","minLength":1},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{
								"type":"object",
								"required":["kind","reference","summary"],
								"properties":{
									"kind":{"type":"string","minLength":1},
									"reference":{"type":"string","minLength":1},
									"summary":{"type":"string","minLength":1}
								},
								"additionalProperties":false
							}}
						},
						"additionalProperties":false
					}},
					"limitations":{"type":"array","maxItems":100,"items":{"type":"string","minLength":1}}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "investigation.answer", Version: 3,
			Document: json.RawMessage(`{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","required":["answer","citations","limitations","limitations_detail"],"properties":{"answer":{"type":"string","minLength":1},"citations":{"type":"array","maxItems":50,"items":{"type":"object","required":["claim","evidence"],"properties":{"claim":{"type":"string","minLength":1},"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{"type":"object","required":["kind","reference","summary"],"properties":{"kind":{"type":"string","minLength":1},"reference":{"type":"string","minLength":1},"summary":{"type":"string","minLength":1}},"additionalProperties":false}}},"additionalProperties":false}},"limitations":{"type":"array","maxItems":10,"items":{"type":"string","minLength":1}},"limitations_detail":{"type":"object","required":["artifact_id","total_count","displayed_count","omitted_count","normalization_version"],"properties":{"artifact_id":{"type":"string","pattern":"^art_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"total_count":{"type":"integer","minimum":0},"displayed_count":{"type":"integer","minimum":0},"omitted_count":{"type":"integer","minimum":0},"normalization_version":{"type":"string","minLength":1}},"additionalProperties":false}},"additionalProperties":false}`),
		},
		{
			ID: "review.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["subject","categories","policy_hash"],
				"properties":{
					"subject":{"type":"object"},
					"categories":{"type":"array","minItems":1,"items":{"type":"string","minLength":1}},
					"policy_hash":{"type":"string","minLength":1}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "review.report", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["coverage","findings","uncertainties","summary"],
				"properties":{
					"coverage":{"type":"array","items":{"$ref":"#/$defs/coverage"}},
					"findings":{"type":"array","maxItems":100,"items":{"$ref":"#/$defs/finding"}},
					"uncertainties":{"type":"array","items":{"$ref":"#/$defs/uncertainty"}},
					"summary":{"type":"string","minLength":1}
				},
				"additionalProperties":false,
				"$defs":{
					"coverage":{
						"type":"object",
						"required":["category","covered","summary"],
						"properties":{
							"category":{"type":"string","minLength":1},
							"covered":{"type":"boolean"},
							"summary":{"type":"string"}
						},
						"additionalProperties":false
					},
					"uncertainty":{
						"type":"object",
						"required":["category","summary"],
						"properties":{
							"category":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					},
					"evidence":{
						"type":"object",
						"required":["kind","ref","hash","summary"],
						"properties":{
							"kind":{"type":"string","minLength":1},
							"ref":{"type":"string","minLength":1},
							"hash":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					},
					"location":{
						"type":"object",
						"properties":{
							"path":{"type":"string"},
							"field":{"type":"string"},
							"start_line":{"type":"integer","minimum":0},
							"end_line":{"type":"integer","minimum":0}
						},
						"additionalProperties":false
					},
					"finding":{
						"type":"object",
						"required":["category","severity","claim","impact","evidence","recommendation","confidence"],
						"properties":{
							"category":{"type":"string","minLength":1},
							"severity":{"enum":["critical","high","medium","low","info"]},
							"claim":{"type":"string","minLength":1},
							"impact":{"type":"string","minLength":1},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{"$ref":"#/$defs/evidence"}},
							"location":{"$ref":"#/$defs/location"},
							"recommendation":{"type":"string","minLength":1},
							"confidence":{"type":"number","minimum":0,"maximum":1}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "review.adjudication.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["subject","policy_hash","fingerprint","findings"],
				"properties":{
					"subject":{"type":"object"},
					"policy_hash":{"type":"string","minLength":1},
					"fingerprint":{"type":"string","minLength":1},
					"findings":{"type":"array","minItems":2,"items":{"type":"object"}}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "review.adjudication", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["decision","rationale"],
				"properties":{
					"decision":{"enum":["confirmed","not_supported","distinct_findings","needs_human"]},
					"rationale":{"type":"string","minLength":1}
				},
				"additionalProperties":false
			}`),
		},
	}
}
