package catalog

import (
	"encoding/json"

	agentapi "github.com/dekwanlabs/nasuta/agent"
)

// DefaultSchemas returns the versioned contracts shipped with the standard Agent definitions.
func DefaultSchemas() []agentapi.SchemaDefinition {
	return []agentapi.SchemaDefinition{
		{
			ID: "qa.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["question"],
				"properties":{"question":{"type":"string","minLength":1}},
				"additionalProperties":false
			}`),
		},
		{
			ID: "qa.answer", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"string",
				"minLength":1
			}`),
		},
		{
			ID: "investigation.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["question"],
				"properties":{"question":{"type":"string","minLength":1,"maxLength":8000}},
				"additionalProperties":false
			}`),
		},
		{
			ID: "task.contract", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["task_id","question","objective","entities","evidence_goals","context"],
				"properties":{
					"task_id":{"type":"string","minLength":1},
					"question":{"type":"string","minLength":1,"maxLength":8000},
					"objective":{"type":"string","minLength":1,"maxLength":8000},
					"entities":{
						"type":"array",
						"maxItems":50,
						"items":{
							"type":"object",
							"required":["id"],
							"properties":{"id":{"type":"string","minLength":1}},
							"additionalProperties":false
						}
					},
					"investigation_goals":{
						"type":"array",
						"maxItems":4,
						"items":{
							"type":"object",
							"required":["id","objective","independently_useful","depends_on"],
							"properties":{
								"id":{"type":"string","pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"},
								"objective":{"type":"string","minLength":1,"maxLength":500},
								"independently_useful":{"type":"boolean"},
								"depends_on":{
									"type":"array",
									"maxItems":3,
									"uniqueItems":true,
									"items":{"type":"string","pattern":"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"}
								}
							},
							"additionalProperties":false
						}
					},
					"evidence_goals":{
						"type":"array",
						"maxItems":50,
						"items":{
							"type":"object",
							"required":["id","facet","required","sources","freshness","minimum_coverage"],
							"properties":{
								"id":{"type":"string","minLength":1},
								"facet":{"type":"string","minLength":1},
								"required":{"type":"boolean"},
								"sources":{
									"type":"array",
									"maxItems":4,
									"uniqueItems":true,
									"items":{"enum":["internal","memory","web","runtime"]}
								},
								"freshness":{"enum":["stable","current","bounded_live"]},
								"minimum_coverage":{"type":"integer","minimum":1,"maximum":50},
								"high_risk":{"type":"boolean"}
							},
							"additionalProperties":false
						}
					},
					"context":{"$ref":"#/$defs/context"}
				},
				"additionalProperties":false,
				"$defs":{
					"context":{
						"type":"object",
						"properties":{
							"conversation_refs":{
								"type":"array",
								"maxItems":100,
								"items":{"$ref":"#/$defs/conversation_ref"}
							},
							"time_range":{"$ref":"#/$defs/time_range"},
							"seed_material":{
								"type":"array",
								"maxItems":20,
								"items":{"$ref":"#/$defs/context_block"}
							}
						},
						"additionalProperties":false
					},
					"conversation_ref":{
						"type":"object",
						"properties":{
							"session_id":{"type":"string","minLength":1},
							"run_id":{"type":"string","minLength":1},
							"turn":{"type":"integer","minimum":1}
						},
						"minProperties":1,
						"additionalProperties":false
					},
					"time_range":{
						"type":"object",
						"required":["from","to","to_exclusive"],
						"properties":{
							"from":{"type":"string","format":"date-time"},
							"to":{"type":"string","format":"date-time"},
							"to_exclusive":{"type":"boolean"},
							"raw":{"type":"string"}
						},
						"additionalProperties":false
					},
					"coverage":{
						"type":"object",
						"properties":{
							"complete":{"type":"boolean"},
							"partial":{"type":"boolean"},
							"included":{"type":"integer","minimum":0},
							"omitted_items":{"type":"integer","minimum":0},
							"next_cursor":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence":{
						"type":"object",
						"required":["source_kind","target","coverage"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"sections":{"type":"array","items":{"type":"string","minLength":1}},
							"content_hash":{"type":"string"},
							"coverage":{"$ref":"#/$defs/coverage"},
							"facets":{"type":"array","items":{"type":"string","minLength":1}},
							"trust_tier":{"type":"integer","minimum":0},
							"evidence_class":{"type":"string"},
							"token_cost":{"type":"integer","minimum":0},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"reference":{
						"type":"object",
						"required":["type","target"],
						"properties":{
							"type":{"type":"string","minLength":1},
							"label":{"type":"string"},
							"target":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					},
					"evidence_identity":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_conflict":{
						"type":"object",
						"required":["identity","current","incoming"],
						"properties":{
							"identity":{"$ref":"#/$defs/evidence_identity"},
							"current":{"$ref":"#/$defs/evidence"},
							"incoming":{"$ref":"#/$defs/evidence"},
							"current_origin":{"type":"string"},
							"incoming_origin":{"type":"string"}
						},
						"additionalProperties":false
					},
					"context_block":{
						"type":"object",
						"required":["source","title","content","complete","content_hash"],
						"properties":{
							"source":{"type":"string","minLength":1},
							"title":{"type":"string","minLength":1},
							"content":{"type":"string","maxLength":200000},
							"references":{
								"type":"array",
								"maxItems":200,
								"items":{"$ref":"#/$defs/reference"}
							},
							"evidence":{
								"type":"array",
								"maxItems":200,
								"items":{"$ref":"#/$defs/evidence"}
							},
							"evidence_conflicts":{
								"type":"array",
								"maxItems":100,
								"items":{"$ref":"#/$defs/evidence_conflict"}
							},
							"complete":{"type":"boolean"},
							"content_hash":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "investigation.report", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["focus","summary","findings","gaps","covered_goals","unresolved_goals"],
				"properties":{
					"focus":{"enum":["code","runtime","docs","web","memory"]},
					"summary":{"type":"string","minLength":1},
					"findings":{"type":"array","maxItems":50,"items":{"$ref":"#/$defs/finding"}},
					"gaps":{"type":"array","maxItems":20,"items":{"type":"string","minLength":1}},
					"covered_goals":{
						"type":"array",
						"maxItems":50,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					},
					"unresolved_goals":{
						"type":"array",
						"maxItems":50,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					}
				},
				"additionalProperties":false,
				"$defs":{
					"evidence_identity":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence":{
						"type":"object",
						"required":["kind","reference","summary"],
						"properties":{
							"kind":{"type":"string","minLength":1},
							"reference":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1},
							"identity":{"$ref":"#/$defs/evidence_identity"}
						},
						"additionalProperties":false
					},
					"finding":{
						"type":"object",
						"required":["claim","goal_ids","evidence","confidence"],
						"properties":{
							"claim":{"type":"string","minLength":1},
							"goal_ids":{
								"type":"array",
								"minItems":1,
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{"$ref":"#/$defs/evidence"}},
							"confidence":{"type":"number","minimum":0,"maximum":1}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "investigation.bundle", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["handoffs","evidence_units","evidence_conflicts","completeness"],
				"properties":{
					"handoffs":{
						"type":"array",
						"maxItems":50,
						"items":{"$ref":"#/$defs/handoff"}
					},
					"unavailable_tasks":{
						"type":"array",
						"maxItems":50,
						"items":{"$ref":"#/$defs/unavailable_task"}
					},
					"evidence_units":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/evidence_unit"}
					},
					"evidence_conflicts":{
						"type":"array",
						"maxItems":100,
						"items":{"$ref":"#/$defs/evidence_conflict"}
					},
					"convergence":{"$ref":"#/$defs/convergence"},
					"completeness":{"enum":["complete","partial","unavailable"]}
				},
				"additionalProperties":false,
				"$defs":{
					"schema_ref":{
						"type":"object",
						"required":["id","version"],
						"properties":{
							"id":{"type":"string","minLength":1},
							"version":{"type":"integer","minimum":1}
						},
						"additionalProperties":false
					},
					"handoff":{
						"type":"object",
						"required":["producer_node_id","schema","payload","completeness"],
						"properties":{
							"producer_node_id":{"type":"string","minLength":1},
							"schema":{"$ref":"#/$defs/schema_ref"},
							"payload":{"$ref":"#/$defs/report"},
							"completeness":{"enum":["complete","partial","unavailable"]}
						},
						"additionalProperties":false
					},
					"unavailable_task":{
						"type":"object",
						"required":["producer_node_id"],
						"properties":{
							"producer_node_id":{"type":"string","minLength":1},
							"stop_reason":{"enum":[
								"no_new_evidence",
								"no_affordable_task",
								"duplicate_evidence_limit",
								"budget_exhausted",
								"capability_unavailable",
								"needs_clarification"
							]}
						},
						"additionalProperties":false
					},
					"convergence":{
						"type":"object",
						"required":[
							"candidate_count",
							"new_identity_count",
							"duplicate_count",
							"duplicate_ratio"
						],
						"properties":{
							"candidate_count":{"type":"integer","minimum":0},
							"new_identity_count":{"type":"integer","minimum":0},
							"duplicate_count":{"type":"integer","minimum":0},
							"duplicate_ratio":{"type":"number","minimum":0,"maximum":1},
							"max_duplicate_ratio":{"type":"number","exclusiveMinimum":0,"maximum":1}
						},
						"additionalProperties":false
					},
					"report":{
						"type":"object",
						"required":["focus","summary","findings","gaps","covered_goals","unresolved_goals"],
						"properties":{
							"focus":{"enum":["code","runtime","docs","web","memory"]},
							"summary":{"type":"string","minLength":1},
							"findings":{"type":"array","maxItems":50,"items":{"$ref":"#/$defs/finding"}},
							"gaps":{"type":"array","maxItems":20,"items":{"type":"string","minLength":1}},
							"covered_goals":{
								"type":"array",
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"unresolved_goals":{
								"type":"array",
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							}
						},
						"additionalProperties":false
					},
					"evidence":{
						"type":"object",
						"required":["kind","reference","summary"],
						"properties":{
							"kind":{"type":"string","minLength":1},
							"reference":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1},
							"identity":{"$ref":"#/$defs/evidence_identity"}
						},
						"additionalProperties":false
					},
					"coverage":{
						"type":"object",
						"properties":{
							"complete":{"type":"boolean"},
							"partial":{"type":"boolean"},
							"included":{"type":"integer","minimum":0},
							"omitted_items":{"type":"integer","minimum":0},
							"next_cursor":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_unit":{
						"type":"object",
						"required":["source_kind","target","coverage"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"sections":{"type":"array","items":{"type":"string","minLength":1}},
							"content_hash":{"type":"string"},
							"coverage":{"$ref":"#/$defs/coverage"},
							"facets":{"type":"array","items":{"type":"string","minLength":1}},
							"trust_tier":{"type":"integer","minimum":0},
							"evidence_class":{"type":"string"},
							"token_cost":{"type":"integer","minimum":0},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_identity":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_conflict":{
						"type":"object",
						"required":["identity","current","incoming"],
						"properties":{
							"identity":{"$ref":"#/$defs/evidence_identity"},
							"current":{"$ref":"#/$defs/evidence_unit"},
							"incoming":{"$ref":"#/$defs/evidence_unit"},
							"current_origin":{"type":"string"},
							"incoming_origin":{"type":"string"}
						},
						"additionalProperties":false
					},
					"finding":{
						"type":"object",
						"required":["claim","goal_ids","evidence","confidence"],
						"properties":{
							"claim":{"type":"string","minLength":1},
							"goal_ids":{
								"type":"array",
								"minItems":1,
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{"$ref":"#/$defs/evidence"}},
							"confidence":{"type":"number","minimum":0,"maximum":1}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "investigation.verified_bundle", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":[
					"supported_claims",
					"partial_claims",
					"unsupported_claims",
					"partial_goals",
					"unresolved_goals",
					"limitations",
					"evidence_units",
					"evidence_conflicts",
					"omissions",
					"verification",
					"completeness"
				],
				"properties":{
					"supported_claims":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/supported_claim"}
					},
					"partial_claims":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/supported_claim"}
					},
					"unsupported_claims":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/unsupported_claim"}
					},
					"partial_goals":{
						"type":"array",
						"maxItems":50,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					},
					"unresolved_goals":{
						"type":"array",
						"maxItems":50,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					},
					"limitations":{
						"type":"array",
						"maxItems":100,
						"uniqueItems":true,
						"items":{"type":"string","minLength":1}
					},
					"evidence_units":{
						"type":"array",
						"maxItems":200,
						"items":{"$ref":"#/$defs/evidence_unit"}
					},
					"evidence_conflicts":{
						"type":"array",
						"maxItems":100,
						"items":{"$ref":"#/$defs/evidence_conflict"}
					},
					"omissions":{
						"type":"object",
						"required":[
							"claims",
							"goals",
							"limitations",
							"evidence_units",
							"evidence_conflicts"
						],
						"properties":{
							"claims":{"type":"integer","minimum":0},
							"goals":{"type":"integer","minimum":0},
							"limitations":{"type":"integer","minimum":0},
							"evidence_units":{"type":"integer","minimum":0},
							"evidence_conflicts":{"type":"integer","minimum":0}
						},
						"additionalProperties":false
					},
					"verification":{
						"type":"object",
						"required":["decision","stop_reason"],
						"properties":{
							"decision":{"enum":["complete","partial","unavailable"]},
							"stop_reason":{"enum":[
								"required_goals_covered",
								"no_new_evidence",
								"no_affordable_task",
								"duplicate_evidence_limit",
								"verification_failed",
								"deadline_exceeded",
								"budget_exhausted",
								"capability_unavailable",
								"needs_clarification"
							]}
						},
						"additionalProperties":false
					},
					"completeness":{"enum":["complete","partial","unavailable"]}
				},
				"additionalProperties":false,
				"$defs":{
					"evidence":{
						"type":"object",
						"required":["kind","reference","summary"],
						"properties":{
							"kind":{"type":"string","minLength":1},
							"reference":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1},
							"identity":{"$ref":"#/$defs/evidence_identity"}
						},
						"additionalProperties":false
					},
					"supported_claim":{
						"type":"object",
						"required":[
							"producer_node_id",
							"finding_index",
							"claim",
							"goal_ids",
							"evidence",
							"evidence_identities",
							"confidence",
							"support",
							"high_risk"
						],
						"properties":{
							"producer_node_id":{"type":"string","minLength":1},
							"finding_index":{"type":"integer","minimum":0},
							"claim":{"type":"string","minLength":1},
							"goal_ids":{
								"type":"array",
								"minItems":1,
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"evidence":{
								"type":"array",
								"minItems":1,
								"maxItems":20,
								"items":{"$ref":"#/$defs/evidence"}
							},
							"evidence_identities":{
								"type":"array",
								"minItems":1,
								"maxItems":200,
								"uniqueItems":true,
								"items":{"$ref":"#/$defs/evidence_identity"}
							},
							"confidence":{"type":"number","minimum":0,"maximum":1},
							"support":{"enum":["supported","partial"]},
							"high_risk":{"type":"boolean"}
						},
						"additionalProperties":false
					},
					"unsupported_claim":{
						"type":"object",
						"required":[
							"producer_node_id",
							"finding_index",
							"goal_ids",
							"support",
							"high_risk",
							"reason_code"
						],
						"properties":{
							"producer_node_id":{"type":"string","minLength":1},
							"finding_index":{"type":"integer","minimum":0},
							"goal_ids":{
								"type":"array",
								"minItems":1,
								"maxItems":50,
								"uniqueItems":true,
								"items":{"type":"string","minLength":1}
							},
							"support":{"const":"unsupported"},
							"high_risk":{"type":"boolean"},
							"reason_code":{"const":"canonical_evidence_unbound"}
						},
						"additionalProperties":false
					},
					"coverage":{
						"type":"object",
						"properties":{
							"complete":{"type":"boolean"},
							"partial":{"type":"boolean"},
							"included":{"type":"integer","minimum":0},
							"omitted_items":{"type":"integer","minimum":0},
							"next_cursor":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_unit":{
						"type":"object",
						"required":["source_kind","target","coverage"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"sections":{"type":"array","items":{"type":"string","minLength":1}},
							"content_hash":{"type":"string"},
							"coverage":{"$ref":"#/$defs/coverage"},
							"facets":{"type":"array","items":{"type":"string","minLength":1}},
							"trust_tier":{"type":"integer","minimum":0},
							"evidence_class":{"type":"string"},
							"token_cost":{"type":"integer","minimum":0},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_identity":{
						"type":"object",
						"required":["source_kind","target"],
						"properties":{
							"source_kind":{"type":"string","minLength":1},
							"target":{"type":"string","minLength":1},
							"section":{"type":"string"},
							"version":{"type":"string"},
							"time_range":{"type":"string"}
						},
						"additionalProperties":false
					},
					"evidence_conflict":{
						"type":"object",
						"required":["identity","current","incoming"],
						"properties":{
							"identity":{"$ref":"#/$defs/evidence_identity"},
							"current":{"$ref":"#/$defs/evidence_unit"},
							"incoming":{"$ref":"#/$defs/evidence_unit"},
							"current_origin":{"type":"string"},
							"incoming_origin":{"type":"string"}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "investigation.answer", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["answer","citations","limitations"],
				"properties":{
					"answer":{"type":"string","minLength":1},
					"citations":{"type":"array","maxItems":50,"items":{
						"type":"object",
						"required":["claim","evidence"],
						"properties":{
							"claim":{"type":"string","minLength":1},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{
								"type":"object",
								"required":["kind","reference","summary"],
								"properties":{
									"kind":{"type":"string","minLength":1},
									"reference":{"type":"string","minLength":1},
									"summary":{"type":"string","minLength":1}
								},
								"additionalProperties":false
							}}
						},
						"additionalProperties":false
					}},
					"limitations":{"type":"array","maxItems":20,"items":{"type":"string","minLength":1}}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "review.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["subject","categories","policy_hash"],
				"properties":{
					"subject":{"type":"object"},
					"categories":{"type":"array","minItems":1,"items":{"type":"string","minLength":1}},
					"policy_hash":{"type":"string","minLength":1}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "review.report", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["coverage","findings","uncertainties","summary"],
				"properties":{
					"coverage":{"type":"array","items":{"$ref":"#/$defs/coverage"}},
					"findings":{"type":"array","maxItems":100,"items":{"$ref":"#/$defs/finding"}},
					"uncertainties":{"type":"array","items":{"$ref":"#/$defs/uncertainty"}},
					"summary":{"type":"string","minLength":1}
				},
				"additionalProperties":false,
				"$defs":{
					"coverage":{
						"type":"object",
						"required":["category","covered","summary"],
						"properties":{
							"category":{"type":"string","minLength":1},
							"covered":{"type":"boolean"},
							"summary":{"type":"string"}
						},
						"additionalProperties":false
					},
					"uncertainty":{
						"type":"object",
						"required":["category","summary"],
						"properties":{
							"category":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					},
					"evidence":{
						"type":"object",
						"required":["kind","ref","hash","summary"],
						"properties":{
							"kind":{"type":"string","minLength":1},
							"ref":{"type":"string","minLength":1},
							"hash":{"type":"string","minLength":1},
							"summary":{"type":"string","minLength":1}
						},
						"additionalProperties":false
					},
					"location":{
						"type":"object",
						"properties":{
							"path":{"type":"string"},
							"field":{"type":"string"},
							"start_line":{"type":"integer","minimum":0},
							"end_line":{"type":"integer","minimum":0}
						},
						"additionalProperties":false
					},
					"finding":{
						"type":"object",
						"required":["category","severity","claim","impact","evidence","recommendation","confidence"],
						"properties":{
							"category":{"type":"string","minLength":1},
							"severity":{"enum":["critical","high","medium","low","info"]},
							"claim":{"type":"string","minLength":1},
							"impact":{"type":"string","minLength":1},
							"evidence":{"type":"array","minItems":1,"maxItems":20,"items":{"$ref":"#/$defs/evidence"}},
							"location":{"$ref":"#/$defs/location"},
							"recommendation":{"type":"string","minLength":1},
							"confidence":{"type":"number","minimum":0,"maximum":1}
						},
						"additionalProperties":false
					}
				}
			}`),
		},
		{
			ID: "review.adjudication.request", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["subject","policy_hash","fingerprint","findings"],
				"properties":{
					"subject":{"type":"object"},
					"policy_hash":{"type":"string","minLength":1},
					"fingerprint":{"type":"string","minLength":1},
					"findings":{"type":"array","minItems":2,"items":{"type":"object"}}
				},
				"additionalProperties":false
			}`),
		},
		{
			ID: "review.adjudication", Version: 1,
			Document: json.RawMessage(`{
				"$schema":"https://json-schema.org/draft/2020-12/schema",
				"type":"object",
				"required":["decision","rationale"],
				"properties":{
					"decision":{"enum":["confirmed","not_supported","distinct_findings","needs_human"]},
					"rationale":{"type":"string","minLength":1}
				},
				"additionalProperties":false
			}`),
		},
	}
}
