package investigation

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"sync"
	"time"

	agentapi "github.com/dekwanlabs/nasuta/agent"
)

type TaskInputProvider func(ExecutableTask, map[string]json.RawMessage) TaskExecutionInput

type ScheduledTaskResult struct {
	Task   ExecutableTask `json:"task"`
	Status TaskStatus     `json:"status"`
	// BudgetGrant records the protected admission floor assigned to this task;
	// it is diagnostic context, not a private task hard limit.
	BudgetGrant BudgetVector        `json:"budget_grant,omitempty"`
	Result      TaskExecutionResult `json:"result,omitempty"`
	Failure     *RunFailure         `json:"failure,omitempty"`
	Started     time.Time           `json:"started_at,omitempty"`
	Ended       time.Time           `json:"ended_at,omitempty"`
	Attempts    []TaskAttempt       `json:"attempts,omitempty"`
	Discoveries []Discovery         `json:"discoveries,omitempty"`
}

type Scheduler struct {
	Executors           ExecutorRegistry
	Schemas             SchemaResolver
	Ledger              *BudgetLedger
	MaxParallelism      int
	MaxAgentParallelism int
	MaxToolParallelism  int
	OnStart             func(ExecutableTask)
	OnComplete          func(ScheduledTaskResult)
	InitialResults      map[string]ScheduledTaskResult
	InitialOutputs      map[string]json.RawMessage
	// ProtectedAdmissions contains reservations made by the coordinator for
	// downstream stages (for example the verifier). They are already counted
	// in the shared ledger and must be consumed by the matching task instead of
	// being reserved a second time during ordinary batch admission.
	ProtectedAdmissions map[string]BudgetReservation
}

func (scheduler Scheduler) Execute(
	ctx context.Context,
	tasks []ExecutableTask,
	provider TaskInputProvider,
) ([]ScheduledTaskResult, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if scheduler.Executors == nil {
		return nil, fmt.Errorf("executor registry is required")
	}
	if scheduler.Schemas == nil {
		return nil, fmt.Errorf("schema registry is required")
	}
	if scheduler.Ledger == nil {
		return nil, fmt.Errorf("budget ledger is required")
	}
	if scheduler.Ledger != nil {
		ctx = agentapi.WithRunBudgetGate(ctx, scheduler.Ledger)
	}
	if len(tasks) == 0 {
		return nil, nil
	}
	defer scheduler.releaseProtectedAdmissions(tasks)
	if err := validateDependencies(tasks); err != nil {
		return nil, err
	}
	maxParallelism := scheduler.MaxParallelism
	if maxParallelism <= 0 || maxParallelism > len(tasks) {
		maxParallelism = len(tasks)
	}
	agentLimit := scheduler.MaxAgentParallelism
	if agentLimit <= 0 || agentLimit > maxParallelism {
		agentLimit = maxParallelism
	}
	toolLimit := scheduler.MaxToolParallelism
	if toolLimit <= 0 || toolLimit > maxParallelism {
		toolLimit = maxParallelism
	}
	state := make(map[string]ExecutableTask, len(tasks))
	for _, task := range tasks {
		if _, duplicate := state[task.ID]; duplicate {
			return nil, fmt.Errorf("%w: duplicate task %q", ErrPlanInvalid, task.ID)
		}
		if task.Status == "" {
			task.Status = TaskPending
		}
		state[task.ID] = task
	}
	results := make(map[string]ScheduledTaskResult, len(tasks))
	for id, result := range scheduler.InitialResults {
		task, ok := state[id]
		if !ok || !terminalTaskStatus(result.Status) {
			// Resume snapshots may contain stale nodes or an in-flight record.
			// Only a terminal result closes a task in this scheduler invocation.
			continue
		}
		result.Task = task
		results[id] = result
		task.Status = result.Status
		state[id] = task
	}
	outputs := make(map[string]json.RawMessage, len(scheduler.InitialOutputs))
	for id, output := range scheduler.InitialOutputs {
		outputs[id] = append([]byte(nil), output...)
	}
	record := func(result ScheduledTaskResult) {
		results[result.Task.ID] = result
		if scheduler.OnComplete != nil {
			scheduler.OnComplete(result)
		}
	}
	for len(results) < len(tasks) {
		if err := ctx.Err(); err != nil {
			for id, task := range state {
				if _, done := results[id]; done {
					continue
				}
				record(ScheduledTaskResult{
					Task: task, Status: TaskCancelled,
					Failure: contextTaskFailure(err, id),
				})
			}
			return orderedTaskResults(tasks, results), nil
		}
		ready, blocked := scheduler.readyTasks(state, results)
		for _, task := range blocked {
			failure := dependencyFailure(task, results)
			record(ScheduledTaskResult{Task: task, Status: TaskBlocked, Failure: failure})
		}
		if len(ready) == 0 {
			if len(results) == len(tasks) {
				break
			}
			return orderedTaskResults(tasks, results), fmt.Errorf("%w: no ready task remains", ErrTaskNotReady)
		}
		batchTasks := make([]ExecutableTask, 0, minInt(maxParallelism, len(ready)))
		agentRunning := 0
		toolRunning := 0
		for _, task := range ready {
			if len(batchTasks) >= maxParallelism {
				break
			}
			if isAgentExecutor(task.Executor) {
				// A serialized Agent node (Verifier/Composer by default) can
				// never share a batch with another Agent. Investigator nodes
				// generated by the catalog opt into parallel execution.
				if !task.AllowParallel && agentRunning > 0 {
					continue
				}
				if agentRunning >= agentLimit {
					continue
				}
				agentRunning++
			} else {
				if toolRunning >= toolLimit {
					continue
				}
				toolRunning++
			}
			batchTasks = append(batchTasks, task)
		}
		admissions, admittedTasks, rejectedTask, admissionErr := scheduler.admitAgentBatch(batchTasks)
		if admissionErr != nil {
			return orderedTaskResults(tasks, results), fmt.Errorf("admit agent batch: %w", admissionErr)
		}
		if len(admittedTasks) != len(batchTasks) {
			batchTasks = admittedTasks
		}
		if len(batchTasks) == 0 {
			// A single task whose minimum cannot fit can never become runnable
			// by waiting. The admission helper returns the exact rejected Agent;
			// do not infer it from ready[0], whose order is not a scheduling contract.
			if rejectedTask != nil {
				result := ScheduledTaskResult{Task: *rejectedTask, Status: TaskFailed, Started: time.Now().UTC(), Ended: time.Now().UTC(),
					Failure: &RunFailure{Code: FailureBudget, Message: "task minimum budget cannot fit within the run limit", Stage: string(StageExecution), TaskID: rejectedTask.ID}}
				record(result)
				continue
			}
			return orderedTaskResults(tasks, results), fmt.Errorf("%w: no admitted task remains", ErrTaskNotReady)
		}
		batch := make([]ScheduledTaskResult, len(batchTasks))
		var waitGroup sync.WaitGroup
		for index, task := range batchTasks {
			index, task := index, task
			runningTask := task
			runningTask.Status = TaskRunning
			state[task.ID] = runningTask
			if scheduler.OnStart != nil {
				scheduler.OnStart(task)
			}
			waitGroup.Add(1)
			go func() {
				defer waitGroup.Done()
				batch[index] = scheduler.executeOne(ctx, task, provider, outputs, admissions[task.ID])
			}()
		}
		waitGroup.Wait()
		for _, taskResult := range batch {
			record(taskResult)
			completedTask := taskResult.Task
			completedTask.Status = taskResult.Status
			state[taskResult.Task.ID] = completedTask
			if len(taskResult.Result.Output) > 0 {
				outputs[taskResult.Task.ID] = append([]byte(nil), taskResult.Result.Output...)
			}
		}
	}
	return orderedTaskResults(tasks, results), nil
}

func (scheduler Scheduler) executeOne(
	parent context.Context,
	task ExecutableTask,
	provider TaskInputProvider,
	outputs map[string]json.RawMessage,
	preAdmission BudgetReservation,
) ScheduledTaskResult {
	result := ScheduledTaskResult{Task: task, Status: TaskFailed, Started: time.Now().UTC(), BudgetGrant: preAdmission.Grant}
	if scheduler.Ledger == nil {
		result.Failure = &RunFailure{Code: FailureBudget, Message: "budget ledger is required", Stage: string(StageExecution), TaskID: task.ID}
		result.Ended = time.Now().UTC()
		return result
	}
	input := TaskExecutionInput{Task: task}
	if provider != nil {
		input = provider(task, cloneOutputs(outputs))
		input.Task = task
	}
	if err := validateTaskInput(scheduler.Schemas, task, input); err != nil {
		releaseAdmission(preAdmission)
		result.Failure = &RunFailure{Code: FailureSchema, Message: err.Error(), Stage: string(StageExecution), TaskID: task.ID}
		result.Ended = time.Now().UTC()
		return result
	}
	executor, resolveErr := scheduler.Executors.Resolve(task.Executor)
	if resolveErr != nil {
		releaseAdmission(preAdmission)
		result.Failure = &RunFailure{Code: FailureExecution, Message: resolveErr.Error(), Stage: string(StageExecution), TaskID: task.ID}
		result.Ended = time.Now().UTC()
		return result
	}
	maxAttempts := task.Budget.MaxAttempts
	if maxAttempts <= 0 {
		maxAttempts = 1
	}
	if strictInvestigatorReportTask(task) && maxAttempts < 2 {
		// A malformed investigation.report gets exactly one format retry,
		// even when the compiled task omitted an attempts limit.
		maxAttempts = 2
	}
	var lastFailure *RunFailure
	var lastTaskResult TaskExecutionResult
	var totalUsage BudgetVector
	baseTaskBudget := task.Budget.Limit
	for attempt := 1; attempt <= maxAttempts; attempt++ {
		// Model tasks need a run-level preflight when no protected admission
		// covers them. Deterministic tools reserve their exact cost below, so an
		// exhausted model dimension must not block a tool-only task.
		protectedAdmission := attempt == 1 && preAdmission.ID != "" && preAdmission.Grant != (BudgetVector{})
		if !protectedAdmission && isAgentExecutor(task.Executor) {
			if err := scheduler.Ledger.Check(); err != nil {
				releaseAdmission(preAdmission)
				lastFailure = &RunFailure{Code: FailureBudget, Message: err.Error(), Stage: string(StageExecution), TaskID: task.ID}
				// No task artifact exists when the run is rejected before execution.
				// Keep this a hard failure so admission cannot turn the budget cause
				// into a misleading empty-output partial result.
				result.Failure = lastFailure
				result.Attempts = append(result.Attempts, TaskAttempt{Attempt: attempt, StartedAt: time.Now().UTC(), EndedAt: time.Now().UTC(), Status: TaskFailed, Failure: lastFailure})
				break
			}
		}
		taskBudget := baseTaskBudget
		grant := taskBudget
		admissionGrant := grant
		var reservation BudgetReservation
		var err error
		if isAgentExecutor(task.Executor) {
			if attempt == 1 && preAdmission.ID != "" {
				admissionGrant = preAdmission.Grant
			} else {
				admissionGrant, err = scheduler.minimumBudget(task)
			}
		}
		if err != nil {
			lastFailure = &RunFailure{Code: FailureExecution, Message: err.Error(), Stage: string(StageExecution), TaskID: task.ID}
			result.Failure = lastFailure
			result.Attempts = append(result.Attempts, TaskAttempt{Attempt: attempt, StartedAt: time.Now().UTC(), EndedAt: time.Now().UTC(), Status: TaskFailed, Failure: lastFailure})
			break
		}
		if attempt == 1 && preAdmission.ID != "" {
			reservation = preAdmission
		} else if isAgentExecutor(task.Executor) {
			reservation, err = scheduler.Ledger.ReserveAdmission(StageExecution, fmt.Sprintf("%s.attempt.%d", task.ID, attempt), admissionGrant)
		} else {
			reservation, err = scheduler.Ledger.Reserve(StageExecution, fmt.Sprintf("%s.attempt.%d", task.ID, attempt), grant)
		}
		if err != nil {
			lastFailure = &RunFailure{Code: FailureBudget, Message: err.Error(), Stage: string(StageExecution), TaskID: task.ID}
			// Admission failure happens before the executor starts, therefore
			// there is no partial artifact to pass downstream.
			result.Failure = lastFailure
			result.Attempts = append(result.Attempts, TaskAttempt{Attempt: attempt, StartedAt: time.Now().UTC(), EndedAt: time.Now().UTC(), Status: TaskFailed, Failure: lastFailure})
			break
		}
		attemptStarted := time.Now().UTC()
		execCtx := parent
		var cancel context.CancelFunc
		if task.Budget.Limit.Duration > 0 {
			execCtx, cancel = context.WithTimeout(parent, task.Budget.Limit.Duration)
		}
		if isAgentExecutor(task.Executor) {
			execCtx = agentapi.WithRunBudgetGate(execCtx, reservationBudgetGate{
				ledger: scheduler.Ledger,
				id:     reservation.ID,
			})
		}
		attemptInput := input
		attemptInput.Attempt = attempt
		attemptTask := task
		if isAgentExecutor(task.Executor) {
			// RuntimeBudget normally carries explicit task narrowing while the
			// shared ledger remains authoritative. A pre-admitted Verifier is
			// different: its input/output/total role slice was allocated from the
			// Run before Investigators started, so pass that exact slice to the
			// child Run as well.
			attemptTask.Budget.Limit = baseTaskBudget
			attemptInput.Task = attemptTask
			attemptInput.RuntimeBudget = baseTaskBudget
			if task.Executor == ExecutorVerifier && protectedAdmission {
				attemptInput.RuntimeBudget = admissionGrant
			}
		}
		taskResult, execErr := executor.Execute(execCtx, attemptTask, attemptInput)
		execContextErr := execCtx.Err()
		if cancel != nil {
			cancel()
		}
		lastTaskResult = taskResult
		totalUsage = addVector(totalUsage, taskResult.Usage)
		attemptEnded := time.Now().UTC()
		settleErr := reservation.Settle(taskResult.Usage)
		if settleErr != nil {
			log.Printf(
				"[investigation] reservation settle failed task=%s executor=%s reservation=%s grant=%+v actual=%+v: %v",
				task.ID, task.Executor, reservation.ID, reservation.Grant, taskResult.Usage, settleErr,
			)
			// A soft settlement may already have consumed and removed the
			// reservation while reporting the hard-limit overrun. Release is
			// therefore best effort for hard-settlement failures only.
			_ = reservation.Release()
			lastFailure = &RunFailure{Code: FailureBudget, Message: settleErr.Error(), Stage: string(StageExecution), TaskID: task.ID}
			result.Attempts = append(result.Attempts, TaskAttempt{Attempt: attempt, StartedAt: attemptStarted, EndedAt: attemptEnded, Status: TaskFailed, Failure: lastFailure})
			break
		}
		if execErr == nil && taskResult.Failure == nil && execContextErr == nil {
			result.Result = taskResult
			result.Result.Usage = totalUsage
			result.Status = TaskSucceeded
			result.Ended = attemptEnded
			result.Discoveries = append([]Discovery(nil), taskResult.Discoveries...)
			result.Attempts = append(result.Attempts, TaskAttempt{
				Attempt: attempt, StartedAt: attemptStarted, EndedAt: attemptEnded, Status: TaskSucceeded,
			})
			return result
		}
		failure := taskResult.Failure
		if failure == nil && execContextErr != nil {
			failure = contextTaskFailure(execContextErr, task.ID)
		}
		if failure == nil && execErr != nil {
			failure = &RunFailure{Code: FailureExecution, Message: execErr.Error(), Stage: string(StageExecution), TaskID: task.ID}
		}
		if failure == nil {
			failure = &RunFailure{Code: FailureExecution, Message: "task execution failed", Stage: string(StageExecution), TaskID: task.ID}
		}
		status := TaskFailed
		if failure.Code == FailureTimeout || failure.Code == FailureCancelled {
			status = TaskCancelled
		}
		result.Attempts = append(result.Attempts, TaskAttempt{
			Attempt: attempt, StartedAt: attemptStarted, EndedAt: attemptEnded, Status: status, Failure: failure,
		})
		lastFailure = failure
		if !retryableTaskFailure(failure) || attempt >= maxAttempts ||
			(strictInvestigatorReportTask(task) && failure.Code == FailureSchema && attempt >= 2) {
			break
		}
	}
	result.Result = lastTaskResult
	result.Result.Usage = totalUsage
	result.Failure = lastFailure
	if lastFailure != nil && hasAdmissibleArtifacts(task, lastTaskResult) {
		result.Status = TaskPartial
		log.Printf(
			"[investigation] task partial task=%s executor=%s stop_reason=%s evidence=%d claims=%d usage=%+v",
			task.ID, task.Executor, lastFailure.Code, len(lastTaskResult.EvidenceCandidates), len(lastTaskResult.Claims), totalUsage,
		)
	}
	if lastFailure != nil && (lastFailure.Code == FailureTimeout || lastFailure.Code == FailureCancelled) {
		result.Status = TaskCancelled
	}
	result.Ended = time.Now().UTC()
	return result
}

func releaseAdmission(reservation BudgetReservation) {
	if reservation.ID == "" {
		return
	}
	if err := reservation.Release(); err != nil {
		log.Printf("[investigation] admission release failed reservation=%s: %v", reservation.ID, err)
	}
}

func (scheduler Scheduler) isAgentTask(task ExecutableTask) bool {
	return isAgentExecutor(task.Executor)
}

func (scheduler Scheduler) minimumBudget(task ExecutableTask) (BudgetVector, error) {
	executor, err := scheduler.Executors.Resolve(task.Executor)
	if err != nil {
		if errors.Is(err, ErrCapabilityGap) {
			// executeOne reports the missing executor as a task failure; admission
			// has no model contract to inspect in this case.
			return BudgetVector{}, nil
		}
		return BudgetVector{}, fmt.Errorf("resolve executor %q for budget admission: %w", task.Executor, err)
	}
	if provider, ok := executor.(TaskMinimumBudgetProvider); ok {
		grant, providerErr := provider.MinimumBudget(task)
		if providerErr != nil {
			return BudgetVector{}, fmt.Errorf("minimum budget for task %q: %w", task.ID, providerErr)
		}
		return grant, nil
	}
	// Executors without a model contract (including test/custom executors)
	// retain the old zero-token admission semantics.
	return BudgetVector{}, nil
}

func (scheduler Scheduler) admitAgentBatch(tasks []ExecutableTask) (map[string]BudgetReservation, []ExecutableTask, *ExecutableTask, error) {
	admitted := append([]ExecutableTask(nil), tasks...)
	var lastRemoved *ExecutableTask
	for {
		requests := make([]BudgetAdmission, 0, len(admitted))
		for _, task := range admitted {
			if !isAgentExecutor(task.Executor) {
				continue
			}
			if _, protected := scheduler.ProtectedAdmissions[task.ID]; protected {
				continue
			}
			grant, err := scheduler.minimumBudget(task)
			if err != nil {
				return nil, nil, lastRemoved, err
			}
			requests = append(requests, BudgetAdmission{TaskID: task.ID, Grant: grant})
		}
		reservations, err := scheduler.Ledger.ReserveAdmissionGroup(StageExecution, requests)
		if err == nil {
			for _, task := range admitted {
				if protected, ok := scheduler.ProtectedAdmissions[task.ID]; ok {
					reservations[task.ID] = protected
				}
			}
			return reservations, admitted, nil, nil
		}
		if !errors.Is(err, ErrBudgetExceeded) {
			return nil, nil, lastRemoved, err
		}
		remove := -1
		for index := len(admitted) - 1; index >= 0; index-- {
			if isAgentExecutor(admitted[index].Executor) {
				remove = index
				break
			}
		}
		if remove < 0 {
			return nil, nil, lastRemoved, err
		}
		removed := admitted[remove]
		lastRemoved = &removed
		admitted = append(admitted[:remove], admitted[remove+1:]...)
		if len(admitted) == 0 {
			return nil, nil, lastRemoved, nil
		}
	}
}

func (scheduler Scheduler) releaseProtectedAdmissions(tasks []ExecutableTask) {
	if len(scheduler.ProtectedAdmissions) == 0 {
		return
	}
	for _, task := range tasks {
		reservation, ok := scheduler.ProtectedAdmissions[task.ID]
		if !ok || reservation.ID == "" {
			continue
		}
		// A reservation consumed by executeOne has already been settled; release
		// is then a harmless no-op from the scheduler's cleanup perspective.
		_ = reservation.Release()
	}
}

func retryableTaskFailure(failure *RunFailure) bool {
	if failure == nil {
		return false
	}
	if failure.Retryable {
		return true
	}
	switch failure.Code {
	case FailureToolUnavailable, FailureReasoning:
		return true
	default:
		return false
	}
}

func validateTaskInput(schemas SchemaResolver, task ExecutableTask, input TaskExecutionInput) error {
	payload, err := json.Marshal(input)
	if err != nil {
		return fmt.Errorf("task %q input encode failed: %w", task.ID, err)
	}
	validator, ok := schemas.(schemaValidator)
	if !ok || validator == nil {
		return fmt.Errorf("task %q schema registry cannot validate input", task.ID)
	}
	if err := validator.Validate(task.InputSchema, json.RawMessage(payload)); err != nil {
		return fmt.Errorf("task %q input schema: %w", task.ID, err)
	}
	return nil
}

func terminalTaskStatus(status TaskStatus) bool {
	switch status {
	case TaskSucceeded, TaskPartial, TaskFailed, TaskBlocked, TaskCancelled:
		return true
	default:
		return false
	}
}

func dependencyFailure(task ExecutableTask, results map[string]ScheduledTaskResult) *RunFailure {
	for _, dependencyID := range task.Dependencies {
		dependency, ok := results[dependencyID]
		if !ok || dependency.Status == TaskSucceeded || dependency.Status == TaskPartial {
			continue
		}
		failure := RunFailure{
			Code:    FailureExecution,
			Message: fmt.Sprintf("required dependency %q ended with status %q", dependencyID, dependency.Status),
			Stage:   string(StageExecution),
			TaskID:  task.ID,
		}
		if dependency.Failure != nil {
			failure.Message = fmt.Sprintf("required dependency %q failed (%s): %s", dependencyID, dependency.Failure.Code, dependency.Failure.Message)
			failure.Code = dependency.Failure.Code
			failure.Retryable = dependency.Failure.Retryable
		}
		return &failure
	}
	return &RunFailure{
		Code:    FailureExecution,
		Message: fmt.Sprintf("required dependency failed for task %q", task.ID),
		Stage:   string(StageExecution),
		TaskID:  task.ID,
	}
}

func (scheduler Scheduler) readyTasks(
	state map[string]ExecutableTask,
	results map[string]ScheduledTaskResult,
) (ready []ExecutableTask, blocked []ExecutableTask) {
	for _, task := range state {
		if task.Status != TaskPending {
			continue
		}
		allSucceeded := true
		allResolved := true
		dependencyFailed := false
		for _, dependency := range task.Dependencies {
			dependencyResult, exists := results[dependency]
			if !exists {
				allSucceeded = false
				allResolved = false
				continue
			}
			if dependencyResult.Status != TaskSucceeded && dependencyResult.Status != TaskPartial {
				dependencyFailed = true
				allSucceeded = false
			}
		}
		if dependencyFailed && !task.Optional {
			blocked = append(blocked, task)
			continue
		}
		if allResolved && (allSucceeded || (dependencyFailed && task.Optional)) {
			ready = append(ready, task)
		}
	}
	sortTasks(ready)
	sortTasks(blocked)
	return ready, blocked
}

func hasAdmissibleArtifacts(task ExecutableTask, result TaskExecutionResult) bool {
	// Investigator output is an internal report, not the dependency contract.
	// Only content-bearing evidence can unblock verification; an empty fallback
	// report must not hide a budget or runtime failure.
	if task.Executor == ExecutorInvestigator {
		return len(result.EvidenceCandidates) > 0
	}
	if task.Executor == ExecutorVerifier {
		return len(result.Claims) > 0
	}
	return false
}

func contextTaskFailure(err error, taskID string) *RunFailure {
	code := FailureExecution
	if errors.Is(err, context.DeadlineExceeded) {
		code = FailureTimeout
	} else if errors.Is(err, context.Canceled) {
		code = FailureCancelled
	}
	message := "task execution failed"
	if err != nil {
		message = err.Error()
	}
	return &RunFailure{Code: code, Message: message, Stage: string(StageExecution), TaskID: taskID}
}

func orderedTaskResults(tasks []ExecutableTask, results map[string]ScheduledTaskResult) []ScheduledTaskResult {
	out := make([]ScheduledTaskResult, 0, len(tasks))
	for _, task := range tasks {
		if result, ok := results[task.ID]; ok {
			out = append(out, result)
		}
	}
	return out
}

func sortTasks(tasks []ExecutableTask) {
	for i := 1; i < len(tasks); i++ {
		for j := i; j > 0 && tasks[j].ID < tasks[j-1].ID; j-- {
			tasks[j], tasks[j-1] = tasks[j-1], tasks[j]
		}
	}
}

func cloneOutputs(outputs map[string]json.RawMessage) map[string]json.RawMessage {
	cloned := make(map[string]json.RawMessage, len(outputs))
	for id, output := range outputs {
		cloned[id] = append([]byte(nil), output...)
	}
	return cloned
}

func isAgentExecutor(executor ExecutorType) bool {
	switch executor {
	case ExecutorInvestigator, ExecutorVerifier, ExecutorComposer:
		return true
	default:
		return false
	}
}
